spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tw_prod
    username: tw_prod_user
    password: pass
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false